#!/bin/bash

dir=$1
new_rvm=
run_rake_db_seen=

if [ ! $dir ]; then
    echo "Usage: mo-dev <dir>"
    exit
fi

if ! [[ `dpkg -l` =~ libgmp.-dev ]]; then
    echo Installing libgmp
    sudo apt-get install -y libgmp3-dev
else
    echo libgmp already installed
fi

if [ ! -d /home/vagrant/.rvm ]; then
    echo Installing RVM
    gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
    curl -L https://get.rvm.io | bash -s stable
    source /home/vagrant/.rvm/scripts/rvm
    new_rvm=1
    sudo gem install bundle
else
    echo RVM installed
fi

source ~/.rvm/scripts/rvm

cd $dir
if [ ! $? -eq 0 ]; then
    echo "Destination directory, " $dir ", doesn't exist!"
    exit
fi

if [ ! -d mushroom-observer ]; then
    git clone https://github.com/MushroomObserver/mushroom-observer.git
fi

cd mushroom-observer

if [ -f .ruby-version ]; then
    if ! [[ `ruby --version` =~ `cat .ruby-version` ]]; then
        echo "Installing ruby version " `cat .ruby-version`
        rvm install `cat .ruby-version`
    fi
fi

ruby --version

if ! [[ `gem list` =~ "bundle " ]]; then
    echo "Installing bundler"
    gem install bundle
else
    echo "Bundler already installed"
fi

mysql -u mo -pmo mo_development -e ''
if [ ! $? -eq 0 ]; then
    mysql -u root -proot < db/initialize.sql
    mysql -u mo -pmo mo_development < db/vagrant/init.sql
    run_rake_db_seed=1
    echo Created and populated mo_development database
else
    echo mo_development exists
fi

if [ ! -f config/database.yml ]; then
    cp db/vagrant/database.yml config
    echo Copied config/database.yml
else
    echo database.yml exists
fi

for dir in images test_images;
do
    for subdir in thumb 320 640 960 1280 orig;
    do
	if [ ! -d public/$dir/$subdir ]; then
	    mkdir -p public/$dir/$subdir
	    echo Created public/$dir/$subdir
	else
	    echo public/$dir/$subdir exists
	fi
    done
done

if [ ! -f /usr/local/bin/jpegresize ]; then
    sudo gcc script/jpegresize.c -ljpeg -lm -O2 -o /usr/local/bin/jpegresize
    echo Created and installed jpegresize executable
else
    echo jpegresize exists
fi

if [ ! -f /usr/local/bin/exifautotran ]; then
    sudo cp script/exifautotran /usr/local/bin/exifautotran
    sudo chmod 755 /usr/local/bin/exifautotran
    echo Installed exifautotran script
else
    echo exifautotran exists
fi

if [ ! -f /usr/bin/exiftool ]; then
    sudo apt-get install -y libimage-exiftool-perl
    echo Installed exiftool
else
    echo exiftool exists
fi

git pull
bundle install
rake db:migrate
if [ $run_rake_db_seed ]; then
    rake db:seed
fi
rake lang:update
if [ $new_rvm ]; then
    echo "RVM installed.  Run: source /home/vagrant/.rvm/scripts/rvm"
fi
